Repository codeit-fe15-part4/albamate, pull requests merged in 2025-08, with the labels that each got.

#158 [feat] 알바토크 상세 페이지 댓글 CRUD
  src/features/albatalk/api/albatalkApi.ts
  src/features/albatalk/components/albatalk-detail/CommentContent.tsx
  src/features/albatalk/components/albatalk-detail/CommentForm.tsx
  src/features/albatalk/components/albatalk-detail/CommentItem.tsx
  src/features/albatalk/components/albatalk-detail/CommentList.tsx
  src/features/albatalk/components/albatalk-detail/CommentSection.tsx
  src/features/albatalk/components/albatalk-detail/index.tsx
  src/features/albatalk/hooks/useAlbatalk.ts
  src/features/albatalk/schemas/albatalk.schema.ts
Labels: ✨ Feat

#155 [feat] 알바폼 이미지 업로드 구현
  src/features/addform/api/index.ts
  src/features/addform/components/AddformClient.tsx
  src/features/addform/components/RecruitContentForm.tsx
  src/features/addform/queries/mutations.ts
  src/shared/components/common/uploadImage/UploadMultipleImage.tsx
Labels: ✨ Feat

#159 [Feat] 로그인/회원가입/정보입력 구현
  next-auth.d.ts
  package.json
  pnpm-lock.yaml
  src/app/(auth)/layout.tsx
  src/app/api/auth/signup/route.ts
  src/auth.config.ts
  src/features/auth/components/AuthForm.tsx
  src/features/auth/components/AuthFormFields.tsx
  src/features/auth/components/AuthFormItem.tsx
  src/features/auth/components/AuthSns.tsx
  src/features/auth/constants/formFields.ts
  src/features/auth/context/AuthContext.tsx
  src/features/auth/context/AuthContextValue.ts
  src/features/auth/hooks/useAuthSession.ts
  src/features/auth/index.ts
  src/features/auth/schema/auth.schema.ts
  src/features/auth/types/auth.types.ts
  src/features/auth/types/index.ts
  src/features/auth/utils/formTypes.ts
  src/features/myalbalist/api/api.ts
  src/features/myalbalist/queries/queries.ts
  src/shared/components/common/input/AddressSearchModal.tsx
  src/shared/components/common/input/InputFile.tsx
  src/shared/components/common/input/InputFileImage.tsx
  src/shared/components/common/profile/Profile.tsx
  src/shared/components/common/profile/ProfileEdit.tsx
  src/shared/components/ui/KakaoMap.tsx
  src/shared/lib/auth/error-messages.ts
  src/shared/lib/auth/use-session-utils.ts
  src/shared/lib/axios.ts
  tsconfig.tsbuildinfo
Labels: ✨ Feat

#169 [fix] 마이페이지 내 정보 수정하기 수정
  src/features/mypage/components/OwnerInfoEdit.tsx
  src/features/mypage/components/WorkerInfoEdit.tsx
  src/features/mypage/schema/mypage.schema.ts
  src/shared/hooks/useViewport.ts
Labels: 🐛 Fix

#171 [feat] 알바폼 상세 페이지 API 연동
  src/app/layout.tsx
  src/features/alba/api/albaApi.ts
  src/features/alba/api/bookmark.ts
  src/features/alba/components/AlbaCondition.tsx
  src/features/alba/components/AlbaContact.tsx
  src/features/alba/components/AlbaInfo.tsx
  src/features/alba/components/AlbaPage.tsx
  src/features/alba/components/ApplicationList.tsx
  src/features/alba/components/button/ApplyButton.tsx
  src/features/alba/components/button/FloatingButtons.tsx
  src/features/alba/components/modal/ApplicationModal.tsx
  src/features/alba/components/modal/FormDeleteModal.tsx
  src/features/alba/mocks/mockApplicationData.ts
  src/features/alba/mocks/mockData.ts
  src/features/albalist/components/AlbaCard.tsx
  src/features/albalist/components/AlbaListPage.tsx
  src/features/albalist/mocks/mockData.ts
  src/features/albatalk/components/albatalk-detail/CommentItem.tsx
  src/features/albatalk/components/albatalk-item/AlbatalkCardHeader.tsx
  src/features/application/components/application-detail/ApplicationProfile.tsx
  src/features/application/components/application-detail/index.tsx
  src/features/application/queries/queries.ts
  src/features/auth/utils/userType.ts
  src/features/myalbalist/components/MyAlbaCard.tsx
  src/features/mypage/components/OwnerInfoEdit.tsx
  src/features/mypage/components/PwChangeForm.tsx
  src/features/mypage/components/WorkerInfoEdit.tsx
  src/shared/components/alba/AlbaDescription.tsx
  src/shared/components/common/button/FloatingButton.tsx
  src/shared/components/common/popup/EditPopup.tsx
  src/shared/components/ui/KakaoMap.tsx
  src/shared/hooks/useCopy.ts
  src/shared/store/popupStore.ts
  src/shared/store/useApplicationStore.ts
Labels: 🐛 Fix, ✨ Feat

#173 [feat] 알바토크 등록/수정/삭제 API 연동
  src/app/(private)/addtalk/page.tsx
  src/app/(public)/addtalk/page.tsx
  src/app/(public)/albatalk/page.tsx
  src/features/addform/api/index.ts
  src/features/addtalk/components/AddtalkButtons.tsx
  src/features/addtalk/components/AddtalkClient.tsx
  src/features/addtalk/components/AddtalkForm.tsx
  src/features/albatalk/api/albatalkApi.ts
  src/features/albatalk/components/albatalk-detail/AlbatalkDetailContent.tsx
  src/features/albatalk/components/albatalk-form/AddtalkButtons.tsx
  src/features/albatalk/components/albatalk-form/AddtalkClient.tsx
  src/features/albatalk/components/albatalk-form/AddtalkForm.tsx
  src/features/albatalk/components/albatalk-item/AlbatalkCardHeader.tsx
  src/features/albatalk/components/albatalk-item/index.tsx
  src/features/albatalk/hooks/useAlbatalk.ts
  src/features/albatalk/schemas/albatalk.schema.ts
  src/features/apply/api/index.ts
  src/shared/components/common/list/AlbaDropdown.tsx
  src/shared/components/common/uploadImage/UploadSingleImage.tsx
  src/shared/utils/generateUniqueFileName.ts
Labels: 🐛 Fix, ✨ Feat

#178 [feat] 지원내역 상태 수정 및 지원서(이력서) 다운로드
  src/features/albatalk/components/albatalk-detail/CommentForm.tsx
  src/features/albatalk/components/albatalk-form/AddtalkClient.tsx
  src/features/albatalk/components/albatalk-item/index.tsx
  src/features/application/api/applicationDetail.ts
  src/features/application/components/application-detail/ApplicationProfile.tsx
  src/features/application/components/application-detail/ApplicationState.tsx
  src/features/application/components/application-detail/ApplicationStateModal.tsx
  src/features/application/components/application-detail/index.tsx
  src/features/application/queries/queries.ts
Labels: 🐛 Fix, ✨ Feat

#180 [fix] 마이페이지 개선 작업
  src/features/apply/api/index.ts
  src/features/mypage/api/api.ts
  src/features/mypage/components/CommentEdit.tsx
  src/features/mypage/components/MixedSection.tsx
  src/features/mypage/components/MyCommentCard.tsx
  src/features/mypage/components/MyPageContent.tsx
  src/features/mypage/components/MyPageTopButtons.tsx
  src/features/mypage/components/MyPostCard.tsx
  src/features/mypage/queries.ts
  src/features/mypage/utils/renderModalContent.tsx
  src/shared/components/common/button/PrimaryButton.tsx
Labels: 🐛 Fix

#181 [feat] 무한스크롤 적용(알바토크 리스트, 알바토크 댓글 리스트)
  src/app/(public)/layout.tsx
  src/features/albatalk/components/albatalk-detail/AlbatalkDetailHeader.tsx
  src/features/albatalk/components/albatalk-detail/CommentItem.tsx
  src/features/albatalk/components/albatalk-detail/CommentList.tsx
  src/features/albatalk/components/albatalk-detail/CommentSection.tsx
  src/features/albatalk/components/albatalk-form/AddtalkClient.tsx
  src/features/albatalk/components/albatalk-item/AlbatalkCardHeader.tsx
  src/features/albatalk/components/albatalk-item/AlbatalkMetaInfo.tsx
  src/features/albatalk/components/albatalk-item/index.tsx
  src/features/albatalk/components/albatalk-list/AlbatalkListClient.tsx
  src/features/albatalk/hooks/useAlbatalk.ts
  src/features/albatalk/schemas/albatalk.schema.ts
Labels: ✨ Feat

#185 [feat] 알바 목록 무한 스크롤 및 스켈레톤 UI 적용
  src/features/alba/components/AlbaPage.tsx
  src/features/alba/components/ApplicationList.tsx
  src/features/alba/components/PageContent.tsx
  src/features/alba/components/button/FloatingButtons.tsx
  src/features/alba/components/skeleton/AlbaSkeleton.tsx
  src/features/alba/types/AlbaItem.ts
  src/features/albalist/components/AlbaCard.tsx
  src/features/albalist/components/AlbaListPage.tsx
  src/features/albalist/components/InfiniteScroll.tsx
  src/features/albalist/components/skeleton/AlbaCardSkeleton.tsx
  src/features/albalist/components/skeleton/AlbaListSkeleton.tsx
  src/features/albalist/components/skeleton/LoadMoreSkeleton.tsx
  src/shared/components/common/gnb/GnbRenderer.tsx
  src/shared/components/common/list/AlbaCardItem.tsx
Labels: ✨ Feat, 💄 Style

#191 [fix] 댓글 작성 완료 후 데이터 중복 요청 개선
  src/app/(public)/albatalk/[id]/page.tsx
  src/features/albatalk/components/albatalk-detail/CommentSection.tsx
  src/features/albatalk/components/albatalk-detail/index.tsx
  src/features/albatalk/hooks/useAlbatalk.ts
  src/features/application/components/application-detail/index.tsx
Labels: 🐛 Fix

#193 [fix] 회원가입, 404페이지, 내알바폼 등 자잘한 수정
  public/images/not-found.png
  src/app/api/auth/signup/route.ts
  src/app/not-found.tsx
  src/features/auth/components/AuthForm.tsx
  src/features/auth/components/AuthFormItem.tsx
  src/features/auth/constants/formFields.ts
  src/features/auth/utils/routePermissions.ts
  src/features/landing/components/HeroSection.tsx
  src/features/myalbalist/components/MyAlbaList.tsx
  src/shared/components/common/date-picker/index.tsx
Labels: ♻️Refactor, 🐛 Fix

#194 [Fix] 마이페이지 전체적으로 미비한 부분은 수정
  src/features/albatalk/components/albatalk-form/AddtalkClient.tsx
  src/features/mypage/components/MyPostCard.tsx
  src/features/mypage/components/OwnerInfoEdit.tsx
  src/features/mypage/components/WorkerInfoEdit.tsx
  src/features/mypage/schema/mypage.schema.ts
Labels: 🐛 Fix

#195 [Refactor] 최종 수정 및 리팩토링 작업
  src/app/(public)/albalist/page.tsx
  src/app/globals.css
  src/app/layout.tsx
  src/features/alba/components/AlbaCondition.tsx
  src/features/alba/components/AlbaContact.tsx
  src/features/alba/components/AlbaInfo.tsx
  src/features/alba/components/AlbaPage.tsx
  src/features/alba/components/ApplicationList.tsx
  src/features/alba/components/ImageCarousel.tsx
  src/features/alba/components/button/FloatingButtons.tsx
  src/features/albalist/components/AlbaListPage.tsx
  src/features/application/queries/queries.ts
  src/shared/components/ThemeToggle.tsx
  src/shared/components/alba/AlbaDetail.tsx
  src/shared/components/common/gnb/ClientGnbWrapper.tsx
  src/shared/components/common/gnb/landing-gnb/RightMenu.tsx
  src/shared/components/common/list/AlbaCardItem.tsx
  src/shared/components/common/list/AlbaDropdown.tsx
  src/shared/components/common/popup/EditPopup.tsx
  src/shared/components/ui/TitleMarquee.tsx
  src/shared/store/popupStore.ts
  src/shared/types/albaDetail.ts
Labels: ♻️Refactor, 🐛 Fix, 💄 Style

#199 [Fix] 알바 목록 및 폼 상세 페이지 긴급 수정
  src/app/globals.css
  src/features/alba/components/AlbaContact.tsx
  src/features/alba/components/AlbaPage.tsx
  src/features/alba/components/ApplicationList.tsx
  src/features/albalist/components/AlbaCard.tsx
  src/shared/components/common/list/AlbaCardItem.tsx
  src/shared/utils/format.ts
Labels: 🐛 Fix

#198 [fix] 폼 제출 유효성 추가
  src/features/addform/components/AddformButtons.tsx
  src/features/addform/components/AddformClient.tsx
  src/features/addform/components/RecruitConditionForm.tsx
  src/features/addform/components/RecruitContentForm.tsx
  src/features/addform/components/WorkConditionForm.tsx
  src/features/addform/schema/addform.schema.ts
  src/features/albatalk/components/albatalk-form/AddtalkForm.tsx
  src/features/apply/components/ApplyForm.tsx
  src/features/apply/schema/apply.schema.ts
  src/shared/components/common/date-picker/index.tsx
  src/shared/components/common/input-dropdown/index.tsx
  src/shared/components/common/time-picker/TimeSelect.tsx
  src/shared/components/common/time-picker/index.tsx
  src/shared/components/common/week-picker/index.tsx
  src/shared/components/ui/DayCheckbox.tsx
Labels: 🐛 Fix

#202 [fix] 사장님 내 정보 수정하기 수정
  src/features/mypage/components/MyPageAddressSearchModal.tsx
  src/features/mypage/components/MyPageContent.tsx
  src/features/mypage/components/MyPageTopButtons.tsx
  src/features/mypage/components/OwnerInfoEdit.tsx
  src/features/mypage/schema/mypage.schema.ts
Labels: 🐛 Fix

#211 [Refactor] 로깅 정리
  src/shared/lib/axios.ts
Labels: ♻️Refactor

#210 [Refactor] 알바 카드 목록 제목 요소 바깥으로 넘침 해결
  src/shared/components/common/list/AlbaCardItem.tsx
  src/shared/components/ui/TitleMarquee.tsx
Labels: ♻️Refactor, 🐛 Fix

#214 Update README.md
  README.md
Labels: 📦 Chore
