Repository codeit-fe15-part4/albamate, pull requests merged in 2025-07, with the labels that each got.

#17 ✨ [feat] RadioButton 공통 컴포넌트 추가
  src/app/globals.css
  src/app/test/hyeran/page.tsx
  src/shared/components/common/button/RadioButton.tsx
Labels: ✨ Feat

#19 [feat] 다크모드 적용
  .husky/prepare-commit-msg
  package.json
  pnpm-lock.yaml
  src/app/globals.css
  src/app/layout.tsx
  src/app/providers.tsx
  src/app/test/hyeran/page.tsx
  src/app/test/yujin/page.tsx
  src/shared/components/ThemeToggle.tsx
  src/shared/components/common/button/RadioButton.tsx
Labels: 📦 Chore, ✨ Feat

#22 [Feat] Pagination 및 Indicator 구현
  public/icons/chevron-left-black.svg
  public/icons/chevron-right-black.svg
  src/app/globals.css
  src/app/test/donghan/page.tsx
  src/shared/components/common/pagination/CardPagination.tsx
  src/shared/components/common/pagination/Indicator.tsx
  src/shared/components/common/pagination/Paginator.tsx
  src/shared/hooks/useViewport.tsx
Labels: ✨ Feat

#27 [feat] Gnb 컴포넌트 구현
  package.json
  pnpm-lock.yaml
  public/icons/logout.svg
  public/icons/menu-white.svg
  public/icons/mypage.svg
  src/app/albalist/layout.tsx
  src/app/albalist/page.tsx
  src/app/albatalk/layout.tsx
  src/app/albatalk/page.tsx
  src/app/globals.css
  src/app/layout.tsx
  src/app/test/yujin/page.tsx
  src/shared/components/ThemeToggle.tsx
  src/shared/components/common/gnb-menu/GnbMenu.tsx
  src/shared/components/common/gnb/AuthGnb.tsx
  src/shared/components/common/gnb/MainGnb.tsx
  tsconfig.json
Labels: 🐛 Fix, ✨ Feat, 💄 Style

#31 [feat] checkbox 컴포넌트 구현
  src/app/test/hyeran/HyeranClientTest.tsx
  src/app/test/hyeran/page.tsx
  src/shared/components/common/button/Checkbox.tsx
  src/shared/components/common/button/RadioButton.tsx
Labels: ✨ Feat

#34 [feat] Tab 버튼 컴포넌트 구현
  src/app/globals.css
  src/app/test/yujin/page.tsx
  src/shared/components/ThemeToggle.tsx
  src/shared/components/common/gnb-menu/GnbMenu.tsx
  src/shared/components/common/gnb/AuthGnb.tsx
  src/shared/components/common/gnb/MainGnb.tsx
  src/shared/components/common/gnb/MobileNav.tsx
  src/shared/components/common/tap/Tab.tsx
Labels: 🐛 Fix, ✨ Feat, 💄 Style

#35 [Feat] date/time/week picker 컴포넌트 제작
  eslint.config.mjs
  package.json
  pnpm-lock.yaml
  public/icons/calendar-gray.svg
  src/app/day-picker-override.css
  src/app/layout.tsx
  src/app/test/sumin/page.tsx
  src/shared/components/common/date-picker/index.tsx
  src/shared/components/common/input-dropdown/index.tsx
  src/shared/components/common/select/index.tsx
  src/shared/components/common/time-picker/TimeSelect.tsx
  src/shared/components/common/time-picker/index.tsx
  src/shared/components/common/week-picker/index.tsx
  src/shared/components/ui/DayCheckbox.tsx
  src/shared/components/ui/Dropdown.tsx
Labels: ✨ Feat

#36 [feat] 툴팁 컴포넌트 구현
  public/icons/edit.svg
  src/app/globals.css
  src/app/test/yujin/page.tsx
  src/shared/components/common/tab/Tab.tsx
  src/shared/components/common/tooltip/Tooltip.tsx
  src/shared/components/common/tooltip/TooltipContentWrapper.tsx
Labels: 🐛 Fix, ✨ Feat, 💄 Style

#41 [feat] 팝업 컴포넌트 구현
  public/icons/X-error-circle.svg
  src/app/test/yujin/page.tsx
  src/shared/components/common/popup/EditPopup.tsx
  src/shared/components/common/popup/ToastPopup.tsx
Labels: 🐛 Fix, ✨ Feat, 💄 Style

#42 [Feat] 지도 컴포넌트 구현
  .gitignore
  README.md
  package.json
  pnpm-lock.yaml
  src/app/globals.css
  src/app/layout.tsx
  src/app/metadata.ts
  src/app/test/sumin/page.tsx
  src/shared/components/common/date-picker/index.tsx
  src/shared/components/common/input-dropdown/index.tsx
  src/shared/components/common/select/index.tsx
  src/shared/components/common/time-picker/index.tsx
  src/shared/components/ui/CopyAddress.tsx
  src/shared/components/ui/Dropdown.tsx
  src/shared/components/ui/KakaoMap.tsx
  src/shared/hooks/.gitkeep
  src/shared/hooks/useCopy.ts
  src/shared/types/.gitkeep
Labels: ✨ Feat

#44 [feat] input text 컴포넌트 제작
  src/app/test/taesik/page.tsx
  src/shared/components/common/input/Icon.tsx
  src/shared/components/common/input/IconInput.tsx
  src/shared/components/common/input/Input.tsx
  src/shared/components/common/input/Textarea.tsx
  src/shared/components/common/input/inputStyles.ts
Labels: ✨ Feat

#47 [feat] Chip 컴포넌트 구현
  package.json
  pnpm-lock.yaml
  public/icons/bookmark-outlined.svg
  src/app/test/yujin/page.tsx
  src/shared/components/common/chip/Chip.tsx
  src/shared/components/common/popup/EditPopup.tsx
  src/shared/components/common/tooltip/Tooltip.tsx
  src/shared/lib/cn.ts
  tsconfig.json
Labels: 📦 Chore, 🐛 Fix, ✨ Feat, 💄 Style

#53 🐛 Fix: Paginator 상수값 변경 및 배열의 고유 키값 변경
  src/shared/components/common/pagination/Paginator.tsx
Labels: 🐛 Fix

#64 [Feat] 랜딩페이지 구현
  package.json
  pnpm-lock.yaml
  public/favicon.ico
  public/images/landing/albaform-clock.png
  public/images/landing/anywhere-application.png
  public/images/landing/anywhere-icon01.png
  public/images/landing/anywhere-icon02.png
  public/images/landing/apply-girl.png
  public/images/landing/apply-icon01.png
  public/images/landing/apply-icon02.png
  public/images/landing/apply-icon03.png
  public/images/landing/apply-icon04.png
  public/images/landing/hero-file-bg.png
  public/images/landing/hero-file-fw.png
  public/images/landing/hero-file01.png
  public/images/landing/hero-file02.png
  public/images/landing/hero-file03.png
  public/images/landing/hero-file04.png
  public/images/landing/manage-bg.png
  public/logos/logo-dark.svg
  public/logos/logo.svg
  public/logos/symbol-dark.svg
  public/logos/symbol.svg
  src/app/page.tsx
  src/features/.gitkeep
  src/features/landing/components/AlbaformSection.tsx
  src/features/landing/components/AnalogClock.tsx
  src/features/landing/components/AnywhereSection.tsx
  src/features/landing/components/ApplySection.tsx
  src/features/landing/components/FooterSection.tsx
  src/features/landing/components/HeroSection.tsx
  src/features/landing/components/LandingBg.tsx
  src/features/landing/components/LandingButton.tsx
  src/features/landing/components/LandingContainer.tsx
  src/features/landing/components/LandingHeroText.tsx
  src/features/landing/components/LandingSection.tsx
  src/features/landing/components/ManageSection.tsx
  src/features/landing/components/SubTitle.tsx
  src/shared/components/common/gnb/AuthGnb.tsx
  src/shared/components/common/gnb/MainGnb.tsx
Labels: ✨ Feat

#62 [fix] next.config.js 및 metadata의 themeColor의 적용 방법 변경
  next.config.ts
  src/app/layout.tsx
  src/app/metadata.ts
  src/app/viewport.ts
Labels: 🐛 Fix

#74 [Feat] 공통 container 컴포넌트 구현
  src/app/test/sumin/page.tsx
  src/shared/components/container/InnerContainer.tsx
Labels: ✨ Feat

#75 [Feat] loading ui 구현
  package.json
  pnpm-lock.yaml
  src/app/test/sumin/page.tsx
  src/assets/animations/Loading.json
  src/shared/components/ui/LoadingSpinner.tsx
  src/shared/types/declaration.d.ts
  tsconfig.json
Labels: ✨ Feat

#81 [feat] useClickOutside 훅 구현 (외부 클릭 시 닫기 기능)
  .coderabbit/config.yml
  .github/workflows/add-coderabbit.yml
  src/app/test/sumin/page.tsx
  src/app/test/yujin/page.tsx
  src/shared/components/common/date-picker/index.tsx
  src/shared/components/common/input/Input.tsx
  src/shared/components/common/input/Textarea.tsx
  src/shared/components/ui/Dropdown.tsx
  src/shared/hooks/useClickOutside.ts
Labels: 🐛 Fix, ✨ Feat

#82 [feat] 알바토크 목록 페이지 구현
  src/app/(public)/albatalk/layout.tsx
  src/app/(public)/albatalk/page.tsx
  src/features/albatalk/components/post-item/PostCardHeader.tsx
  src/features/albatalk/components/post-item/PostMetaInfo.tsx
  src/features/albatalk/components/post-item/index.tsx
  src/features/albatalk/components/post-list/PostFilterBar.tsx
  src/features/albatalk/components/post-list/index.tsx
  src/features/albatalk/mocks/getPosts.ts
  src/features/albatalk/types/albatalk.ts
  src/shared/components/container/InnerContainer.tsx
  src/shared/utils/date.ts
Labels: ✨ Feat

#91 [feat] 랜딩 페이지 전용 헤더 구현
  .github/workflows/add-coderabbit.yml
  src/app/(public)/layout.tsx
  src/app/globals.css
  src/app/test/yujin/page.tsx
  src/features/albalist/components/AlbaFilterBar.tsx
  src/shared/components/ThemeToggle.tsx
  src/shared/components/common/gnb/NavMenu.tsx
  src/shared/components/common/gnb/auth-gnb/RightMenu.tsx
  src/shared/components/common/gnb/landing-gnb/Header.tsx
  src/shared/components/common/gnb/landing-gnb/RightMenu.tsx
  src/shared/components/common/gnb/landing-gnb/index.tsx
  src/shared/components/common/gnb/main-gnb/Header.tsx
  src/shared/components/common/gnb/main-gnb/NavMenu.tsx
  src/shared/components/common/gnb/styles/Header.styles.ts
Labels: 🐛 Fix, ✨ Feat, 💄 Style

#93 [feat] 알바폼 만들기 페이지 구현
  public/icons/chevron-down-white.svg
  src/app/(owner)/addform/page.tsx
  src/app/(owner)/layout.tsx
  src/app/globals.css
  src/features/owner/addform/components/AddFormSection.tsx
  src/features/owner/addform/components/AddformButtons.tsx
  src/features/owner/addform/components/AddformClient.tsx
  src/features/owner/addform/components/MenuItem.tsx
  src/features/owner/addform/components/NumberCircle.tsx
  src/features/owner/addform/components/RecruitConditionForm.tsx
  src/features/owner/addform/components/RecruitContentForm.tsx
  src/features/owner/addform/components/Sidebar.tsx
  src/features/owner/addform/components/TabMenu.tsx
  src/features/owner/addform/components/WorkConditionForm.tsx
  src/features/owner/addform/components/WritingBadge.tsx
Labels: ✨ Feat

#94 [refactor] 알바 목록 필터/카드 분리 및 재사용 구조 개선
  src/app/(public)/albalist/page.tsx
  src/features/albalist/components/AlbaCard.tsx
  src/features/albalist/components/AlbaFilterBar.tsx
  src/features/albalist/components/AlbaListPage.tsx
  src/features/albalist/mock/mockData.ts
  src/shared/components/common/list/AlbaCardItem.tsx
  src/shared/components/common/list/AlbaDropdown.tsx
  src/shared/components/common/list/FilterBar.tsx
  src/shared/components/common/list/ListWrapper.tsx
  src/shared/constants/filterOptions.ts
  src/shared/types/filter.ts
Labels: ♻️Refactor, 🐛 Fix, 💄 Style

#95 [Feat] 랜딩페이지 반응형 구현
  src/app/(public)/page.tsx
  src/features/landing/components/AlbaformSection.tsx
  src/features/landing/components/AnalogClock.tsx
  src/features/landing/components/AnywhereSection.tsx
  src/features/landing/components/ApplySection.tsx
  src/features/landing/components/FooterSection.tsx
  src/features/landing/components/HeroSection.tsx
  src/features/landing/components/LandingButton.tsx
  src/features/landing/components/LandingContainer.tsx
  src/features/landing/components/LandingHeroText.tsx
  src/features/landing/components/LandingSectionImage.tsx
  src/features/landing/components/ManageSection.tsx
  src/features/landing/components/SubTitle.tsx
  src/features/landing/components/Title.tsx
  src/shared/types/next-auth.d.ts
Labels: 💄 Style

#100 [Feat] 내 알바폼 페이지 구현
  public/images/examples/profile-example01.jpg
  public/images/examples/profile-example02.jpg
  public/images/examples/profile-example03.jpg
  public/images/examples/profile-example04.jpg
  public/images/examples/profile-example05.jpg
  public/images/examples/profile-example06.jpg
  public/images/examples/profile-example07.jpg
  public/images/examples/profile-example08.jpg
  public/images/examples/profile-example09.jpg
  public/images/examples/profile-example10.jpg
  public/images/examples/store-example01.jpg
  public/images/examples/store-example02.jpg
  public/images/examples/store-example03.jpg
  public/images/examples/store-example04.jpg
  public/images/examples/store-example05.jpg
  public/images/examples/store-example06.jpg
  public/images/examples/store-example07.jpg
  public/images/examples/store-example08.jpg
  public/images/examples/store-example09.jpg
  public/images/list-default.png
  src/app/(public)/albalist/page.tsx
  src/app/(public)/myalbalist/page.tsx
  src/app/globals.css
  src/features/landing/components/HeroSection.tsx
  src/features/myalbalist/components/ApplicantAlbaCard.tsx
  src/features/myalbalist/components/MyAlbaCard.tsx
  src/features/myalbalist/components/MyAlbaList.tsx
  src/features/myalbalist/mock/applicantMyAlbaList.ts
  src/features/myalbalist/mock/ownerMyAlbaList.ts
  src/features/myalbalist/types/myalbalist.ts
  src/shared/components/common/chip/Chip.tsx
  src/shared/components/common/gnb/NavMenu.tsx
  src/shared/components/common/gnb/styles/Header.styles.ts
  src/shared/components/common/list/AlbaCardItem.tsx
  src/shared/components/common/list/FilterBar.tsx
  src/shared/components/common/list/ListWrapper.tsx
  src/shared/components/container/InnerContainer.tsx
Labels: ✨ Feat

#102 [feat] 알바 폼 상세 페이지의 AlbaDetail 공통 컴포넌트 구현
  next.config.ts
  src/app/(public)/alba/[formId]/page.tsx
  src/app/globals.css
  src/app/test/yujin/page.tsx
  src/features/alba/components/AlbaApplyButton.tsx
  src/features/alba/components/AlbaCondition.tsx
  src/features/alba/components/AlbaContact.tsx
  src/features/alba/components/AlbaInfo.tsx
  src/features/alba/components/AlbaLocation.tsx
  src/features/alba/components/AlbaPage.tsx
  src/features/alba/mocks/mockData.ts
  src/features/alba/types/MockAlbaItem.ts
  src/features/albalist/components/AlbaListPage.tsx
  src/features/albalist/mock/mockData.ts
  src/features/albalist/mocks/mockData.ts
  src/shared/components/alba/AlbaDescription.tsx
  src/shared/components/alba/AlbaDetail.tsx
  src/shared/components/common/list/AlbaCardItem.tsx
  src/shared/components/common/popup/ToastPopup.tsx
  tsconfig.json
Labels: 🐛 Fix, ✨ Feat, 💄 Style

#124 [feat] 알바폼 상세 페이지 추가 로직 구현
  package.json
  pnpm-lock.yaml
  public/images/modal/empty.svg
  public/images/modal/warning.svg
  public/images/modal/writing.svg
  src/app/globals.css
  src/app/test/yujin/page.tsx
  src/features/alba/api/bookmark.ts
  src/features/alba/components/AlbaContact.tsx
  src/features/alba/components/AlbaInfo.tsx
  src/features/alba/components/AlbaLocation.tsx
  src/features/alba/components/AlbaPage.tsx
  src/features/alba/components/ApplicationList.tsx
  src/features/alba/components/Desktop/AlbaPageDesktop.tsx
  src/features/alba/components/Desktop/ApplyButtonDesktop.tsx
  src/features/alba/components/Tablet/AlbaPageTablet.tsx
  src/features/alba/components/Tablet/ApplyButtonTablet.tsx
  src/features/alba/components/modal/ApplicationModal.tsx
  src/features/alba/components/modal/FormDeleteModal.tsx
  src/features/alba/components/modal/RecruitClosedModal.tsx
  src/features/alba/mocks/mockApplicationData.ts
  src/features/alba/mocks/mockData.ts
  src/features/alba/types/MockApplication.ts
  src/features/albalist/components/AlbaCard.tsx
  src/features/albalist/mocks/mockData.ts
  src/shared/components/alba/AlbaDescription.tsx
  src/shared/components/alba/AlbaDetail.tsx
  src/shared/components/common/button/FloatingButtonContainer.tsx
  src/shared/components/common/chip/Chip.tsx
  src/shared/components/common/chip/label.tsx
  src/shared/components/common/gnb/landing-gnb/RightMenu.tsx
  src/shared/components/common/gnb/main-gnb/Header.tsx
  src/shared/components/common/list/AlbaCardItem.tsx
  src/shared/components/common/list/AlbaDropdown.tsx
  src/shared/components/ui/KakaoMap.tsx
  src/shared/utils/application.ts
  src/shared/utils/format.ts
  src/shared/utils/getCoordsByAddress.ts
Labels: ♻️Refactor, 🐛 Fix, ✨ Feat, 💄 Style

#126 [feat] 지원내역 상세 페이지 통합
  src/app/(owner)/application/[applicationId]/page.tsx
  src/app/(owner)/application/page.tsx
  src/app/(private)/application/[formId]/[applicationId]/layout.tsx
  src/app/(private)/application/[formId]/[applicationId]/page.tsx
  src/app/(private)/layout.tsx
  src/app/(private)/mypage/layout.tsx
  src/app/(worker)/myapply/[formId]/page.tsx
  src/app/(worker)/myapply/layout.tsx
  src/app/(worker)/myapply/page.tsx
  src/features/albatalk/components/post-item/PostMetaInfo.tsx
  src/features/albatalk/components/post-item/index.tsx
  src/features/albatalk/components/post-list/PostFilterBar.tsx
  src/features/albatalk/components/post-list/index.tsx
  src/features/apply/components/apply-detail/ApplyState.tsx
  src/features/apply/components/apply-detail/index.tsx
  src/features/mypage/components/MixedSection.tsx
  src/features/mypage/components/MyCommentCard.tsx
  src/features/mypage/components/MyPageDropDown.tsx
  src/features/mypage/components/MyPageTopButtons.tsx
  src/features/mypage/components/MyPostCard.tsx
  src/shared/components/common/kebabMenuDropdown/index.tsx
Labels: 🐛 Fix, ✨ Feat, 💄 Style

#125 [feat] api 기초 세팅
  src/features/common/api.ts
  src/features/user/api.ts
  src/shared/lib/axios.ts
  src/shared/types/mypage.ts
Labels: ✨ Feat

#128 [Feat] auth, 로그인, 인증관련 유틸리티 함수 구현
  next-auth.d.ts
  src/app/(auth)/layout.tsx
  src/app/(private)/myalbalist/page.tsx
  src/app/api/auth/[...nextauth]/route.ts
  src/app/layout.tsx
  src/auth.config.ts
  src/auth.ts
  src/features/auth/README.md
  src/features/auth/components/AuthForm.tsx
  src/features/auth/components/AuthFormFields.tsx
  src/features/auth/components/AuthSns.tsx
  src/features/auth/components/AuthTitleArea.tsx
  src/features/auth/constants/auth.message.ts
  src/features/auth/constants/authContent.ts
  src/features/auth/constants/formFields.ts
  src/features/auth/constants/route.ts
  src/features/auth/context/AuthContext.tsx
  src/features/auth/hooks/index.ts
  src/features/auth/hooks/useAuth.ts
  src/features/auth/hooks/useAuthForm.ts
  src/features/auth/hooks/useAuthNavigation.ts
  src/features/auth/hooks/useAuthSession.ts
  src/features/auth/index.ts
  src/features/auth/mocks/index.ts
  src/features/auth/schema/auth.schema.ts
  src/features/auth/types/auth.types.ts
  src/features/auth/types/index.ts
  src/features/auth/utils/authContent.ts
  src/features/auth/utils/authUtils.ts
  src/features/auth/utils/formTypes.ts
  src/features/auth/utils/userType.ts
  src/features/myalbalist/components/MyAlbaList.tsx
  src/features/myalbalist/mock/applicantMyAlbaList.ts
  src/features/myalbalist/mock/ownerMyAlbaList.ts
  src/middleware.ts
  src/shared/components/common/gnb/auth-gnb/MobileNav.tsx
  src/shared/components/common/gnb/auth-gnb/RightMenu.tsx
  src/shared/components/common/gnb/auth-gnb/index.tsx
  src/shared/lib/auth/session-query.ts
  src/shared/lib/auth/use-session-utils.ts
  src/shared/types/next-auth.d.ts
  tsconfig.json
Labels: ✨ Feat

#135 [Fix] auth type error 해결
  src/features/auth/components/AuthForm.tsx
  src/features/auth/components/AuthFormFields.tsx
  src/features/auth/utils/formTypes.ts
  src/features/myalbalist/api/api.ts
Labels: 🐛 Fix

#131 [feat] 지원내역 상세 페이지 모달, 툴팁 반영
  src/app/test/yujin/page.tsx
  src/features/apply/components/apply-detail/ApplyProfile.tsx
  src/features/apply/components/apply-detail/ApplyState.tsx
  src/features/apply/components/apply-detail/ApplyStateModal.tsx
  src/features/apply/components/apply-detail/index.tsx
  src/shared/components/common/button/RadioButton.tsx
  src/shared/components/common/tooltip/Tooltip.tsx
  src/shared/utils/format.ts
Labels: 🐛 Fix, ✨ Feat

#136 [feat] 전체 페이지 헤더 통합 작업
  src/app/(auth)/layout.tsx
  src/app/(owner)/layout.tsx
  src/app/(private)/layout.tsx
  src/app/(private)/mypage/layout.tsx
  src/app/(public)/albalist/page.tsx
  src/app/(public)/layout.tsx
  src/app/(worker)/layout.tsx
  src/app/globals.css
  src/app/layout.tsx
  src/app/test/sumin/page.tsx
  src/app/test/yujin/page.tsx
  src/features/alba/components/AlbaPage.tsx
  src/features/alba/components/ApplicationList.tsx
  src/features/alba/components/Tablet/AlbaPageTablet.tsx
  src/features/alba/components/Tablet/ApplyButtonTablet.tsx
  src/features/alba/components/modal/ApplicationModal.tsx
  src/features/alba/components/modal/FormDeleteModal.tsx
  src/features/alba/components/modal/RecruitClosedModal.tsx
  src/features/alba/mocks/mockData.ts
  src/features/albalist/components/AlbaListPage.tsx
  src/shared/components/common/gnb-menu/GnbMenu.tsx
  src/shared/components/common/gnb/GnbRenderer.tsx
  src/shared/components/common/list/AlbaDropdown.tsx
  src/shared/components/common/modal/ModalContent.tsx
  src/shared/components/common/select/index.tsx
  src/shared/components/ui/KakaoMap.tsx
  src/shared/utils/application.ts
  src/shared/utils/getCoordsByAddress.ts
Labels: ✨ Feat

#141 [fix] 메타태그 수정
  src/app/layout.tsx
  src/app/metadata.ts
  src/app/viewport.ts
Labels: 🐛 Fix

#143 [feat] 지원내역 상세 페이지 폴더 구조 정리 및 API 연동
  src/app/(private)/application/[applicationId]/form/[formId]/page.tsx
  src/app/(private)/application/[applicationId]/form/layout.tsx
  src/app/(private)/application/[formId]/[applicationId]/page.tsx
  src/app/(private)/myapply/[formId]/page.tsx
  src/app/test/hyeran/HyeranClientTest.tsx
  src/features/alba/components/AlbaPage.tsx
  src/features/application/api/applicationDetail.ts
  src/features/application/components/application-detail/ApplicationProfile.tsx
  src/features/application/components/application-detail/ApplicationState.tsx
  src/features/application/components/application-detail/ApplicationStateModal.tsx
  src/features/application/components/application-detail/index.tsx
  src/features/application/queries/queries.ts
  src/features/application/types/application.ts
  src/features/apply/components/apply-detail/index.tsx
  src/features/apply/mocks/mockApplyDetail.ts
  src/features/auth/utils/userType.ts
  src/shared/components/common/imageCarousel/ImageCarousel.tsx
  src/shared/components/common/imageCarousel/carousel.ts
  src/shared/components/common/imageCarousel/useCarousel.ts
  src/shared/components/common/imageCarousel/useSwipeGesture.ts
  src/shared/components/common/pagination/Indicator.tsx
  src/shared/utils/carousel.ts
Labels: 🐛 Fix, ✨ Feat

#147 [feat] 알바 지원하기 페이지 구현 (비회원)
  src/app/(public)/apply/[formId]/page.tsx
  src/features/apply/api/index.ts
  src/features/apply/components/ApplyForm.tsx
  src/features/apply/components/ApplyFormList.tsx
  src/features/apply/queries/mutations.ts
  src/features/apply/schema/apply.schema.ts
Labels: ✨ Feat

#149 [feat] 알바토크 목록 페이지 API 연동
  src/app/(public)/albatalk/page.tsx
  src/features/albatalk/api/albatalkApi.ts
  src/features/albatalk/components/albatalk-detail/AlbatalkDetailHeader.tsx
  src/features/albatalk/components/albatalk-detail/CommentItem.tsx
  src/features/albatalk/components/albatalk-detail/CommentList.tsx
  src/features/albatalk/components/albatalk-detail/CommentSection.tsx
  src/features/albatalk/components/albatalk-detail/index.tsx
  src/features/albatalk/components/albatalk-item/AlbatalkCardHeader.tsx
  src/features/albatalk/components/albatalk-item/AlbatalkMetaInfo.tsx
  src/features/albatalk/components/albatalk-item/AlbatalkMetaInfoUser.tsx
  src/features/albatalk/components/albatalk-item/index.tsx
  src/features/albatalk/components/albatalk-list/AlbatalkFilterBar.tsx
  src/features/albatalk/components/albatalk-list/AlbatalkListClient.tsx
  src/features/albatalk/components/post-item/PostMetaInfo.tsx
  src/features/albatalk/components/post-item/index.tsx
  src/features/albatalk/components/post-list/PostFilterBar.tsx
  src/features/albatalk/components/post-list/index.tsx
  src/features/albatalk/constants/albatalk.constants.ts
  src/features/albatalk/hooks/useAlbatalk.ts
  src/features/albatalk/mocks/getPosts.ts
  src/features/albatalk/mocks/mockAlbatalkComments.ts
  src/features/albatalk/mocks/mockAlbatalkDetail.ts
  src/features/albatalk/schemas/albatalk.schema.ts
  src/features/albatalk/types/albatalk.ts
  src/features/application/queries/queries.ts
  src/shared/constants/zIndex.ts
  src/shared/utils/date.ts
Labels: ♻️Refactor, ✨ Feat

#154 [feat] 알바 목록 페이지 API 구현
  next.config.ts
  src/app/(public)/albalist/page.tsx
  src/features/alba/components/AlbaPage.tsx
  src/features/alba/components/Desktop/AlbaPageDesktop.tsx
  src/features/alba/components/Desktop/ApplyButtonDesktop.tsx
  src/features/alba/components/ImageCarousel.tsx
  src/features/alba/components/PageContent.tsx
  src/features/alba/components/Tablet/AlbaPageTablet.tsx
  src/features/alba/components/Tablet/ApplyButtonTablet.tsx
  src/features/alba/components/button/ApplicantButtons.tsx
  src/features/alba/components/button/ApplyButton.tsx
  src/features/alba/components/button/FloatingButtons.tsx
  src/features/alba/components/button/OwnerButtons.tsx
  src/features/alba/components/modal/ApplicationModal.tsx
  src/features/albalist/api/albaListApi.ts
  src/features/albalist/components/AlbaCard.tsx
  src/features/albalist/components/AlbaFilterBar.tsx
  src/features/albalist/components/AlbaListPage.tsx
  src/features/albalist/queries/queries.ts
  src/features/albalist/utils/filterUtils.ts
  src/shared/components/common/gnb/GnbRenderer.tsx
  src/shared/components/common/list/AlbaCardItem.tsx
  src/shared/components/common/list/FilterBar.tsx
  src/shared/components/ui/CopyAddress.tsx
  src/shared/types/filter.ts
Labels: 🐛 Fix, ✨ Feat
